### ISSUE TITLE
com.intellij.diagnostic.PluginException: com.dsoftware.ghmanager.psi.OutdatedVersionAnnotator PluginClassLoader(plugin=PluginDescriptor(name=GitHub Actions Manager, id=com.dsoftware.ghtoolbar, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PyCharm2024.1/plugins/github-actions-manager, version=1.21.5, package=null, isBundled=false), packagePrefix=null, state=active)

### ISSUE THREAD

**Issue by edjchapman** [dsoftwareinc/ghactions-manager#131]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

#### Stack trace

com.intellij.diagnostic.PluginException: com.dsoftware.ghmanager.psi.OutdatedVersionAnnotator PluginClassLoader(plugin=PluginDescriptor(name=GitHub Actions Manager, id=com.dsoftware.ghtoolbar, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PyCharm2024.1/plugins/github-actions-manager, version=1.21.5, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:951)
	at com.intellij.serviceContainer.LazyExtensionInstance.createInstance(LazyExtensionInstance.java:55)
	at com.intellij.serviceContainer.LazyExtensionInstance.getInstance(LazyExtensionInstance.java:44)
	at com.intellij.serviceContainer.BaseKeyedLazyInstance.getInstance(BaseKeyedLazyInstance.java:38)
	at com.intellij.openapi.util.KeyedExtensionCollector.instantiate(KeyedExtensionCollector.java:199)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensionsFromExtensionPoint(KeyedExtensionCollector.java:161)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:134)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:134)
	at com.intellij.lang.LanguageExtension.buildExtensions(LanguageExtension.java:19)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:111)
	at com.intellij.lang.LanguageExtension.collectAllForLanguage(LanguageExtension.java:125)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:118)
	at com.intellij.lang.LanguageExtension.allForLanguageOrAny(LanguageExtension.java:146)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.calcSupportedLanguages(AnnotatorRunner.java:111)
	at com.intellij.codeInsight.daemon.impl.AnnotatorRunner.runAnnotatorsAsync(AnnotatorRunner.java:69)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:329)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:239)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:109)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:413)
	at com.intellij.openapi.application.impl.RwLockHolder.tryRunReadAction(RwLockHolder.kt:310)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:958)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:404)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:403)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:379)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:795)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:199)
	at com.intellij.openapi.application.impl.RwLockHolder.executeByImpatientReader(RwLockHolder.kt:491)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:377)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: com.dsoftware.ghmanager.psi.OutdatedVersionAnnotator PluginClassLoader(plugin=PluginDescriptor(name=GitHub Actions Manager, id=com.dsoftware.ghtoolbar, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PyCharm2024.1/plugins/github-actions-manager, version=1.21.5, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1466)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:943)
	... 44 more

### Additional context

Plugin version: 1.21.5
IDE: PyCharm 2024.1 (PY-241.14494.241)
OS: macOS 14.4.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/cunla) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/cunla/ghactions-manager/issues/131">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/cunla/ghactions-manager/issues/131/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/cunla/ghactions-manager/issues/131/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Hi @edjchapman, thanks for reporting this.
Can you elaborate when does this happen? The stacktrace does not contain any of the plugin code and I am not sure how to replicate this.

**Comment by edjchapman** [comment]
Sorry I just clicked some buttons and it triggered this, I didn't realise it would do that.  Next time I come across it I'll make sure to add some more useful information!

**Comment by cunla** [comment]
I think I figured it out. I'll publish a fix and it should be available next week.

**Comment by cunla** [comment]
Fixed in 1.21.6 - should be available this week
