### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jetbrains/yaml/psi/YAMLKeyValue

### ISSUE THREAD

**Issue by fan-tom** [dsoftwareinc/ghactions-manager#153]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

Unhandled exception in [ComponentManager(ProjectImpl@858641939), CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelling}@7eff8e08, Dispatchers.Default]

#### Stack trace

java.lang.NoClassDefFoundError: org/jetbrains/yaml/psi/YAMLKeyValue
	at com.dsoftware.ghmanager.psi.Tools.getYamlElementsWithKey(Tools.kt:35)
	at com.dsoftware.ghmanager.psi.ProjectStartup$scanWorkflowFile$1.invoke(ProjectStartup.kt:52)
	at com.dsoftware.ghmanager.psi.ProjectStartup$scanWorkflowFile$1.invoke(ProjectStartup.kt:50)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at com.dsoftware.ghmanager.psi.ProjectStartup.scanWorkflowFile(ProjectStartup.kt:50)
	at com.dsoftware.ghmanager.psi.ProjectStartup$execute$3.invoke(ProjectStartup.kt:34)
	at com.dsoftware.ghmanager.psi.ProjectStartup$execute$3.invoke(ProjectStartup.kt:26)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at com.dsoftware.ghmanager.psi.ProjectStartup.execute(ProjectStartup.kt:26)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:473)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@858641939), CoroutineName(run activity), run activity, StandaloneCoroutine{Cancelled}@7eff8e08, Dispatchers.Default]
Caused by: java.lang.ClassNotFoundException: org.jetbrains.yaml.psi.YAMLKeyValue PluginClassLoader(plugin=PluginDescriptor(name=GitHub Actions Manager, id=com.dsoftware.ghtoolbar, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2024.1/plugins/github-actions-manager, version=1.22.0, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 22 more

### Additional context

Plugin version: 1.22.0
IDE: IntelliJ IDEA 2024.1.2 Preview (IC-241.17011.2)
OS: macOS 14.4.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/153">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/153/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/153/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Fixed in 2024.1.1
