### ISSUE TITLE
Unable to save plugin settings

### ISSUE THREAD

**Issue by xerullian** [dsoftwareinc/ghactions-manager#155]
### Describe the bug
Add a screenshot if it is relevant.

**Describe the bug:**

"The plugin *com.dsoftware.ghtoolbar* failed to save settings. Please restart webstorm."

![image](https://github.com/dsoftwareinc/ghactions-manager/assets/7705061/33b04feb-bd73-490e-a818-2e51a3cfc11d)

### Steps to reproduce

Regular IDE usage. 
### Expected behavior

No error message with normal IDE usage.

### Additional context

Plugin version: 2024.1.1
IDE: WebStorm 2024.1.3 EAP
OS: Nobara Linux

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/155">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/155/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/155/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
@xerullian thanks for reporting. Can you share the relevant parts of the log? (Help -> Open log in Editor -> Anything with `com.dsoftware.*`)

**Comment by xerullian** [comment]
@cunla On Webstorm 2024.1 EAP it stopped showing up consistently and hasn't since. That may be related to me disabling/renabling the notification. 

I'm on WebStorm 2024.2 EAP with default notification settings and it's showing again.

This looks like it may be the relevant part of the log.

```
2024-05-16 16:00:53,147 [4485153]   WARN - #c.i.o.c.i.s.StoreUtil - Save settings failed
java.lang.Exception: Cannot get GhActionsManagerSettings.ActionsDataCache component state
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$suspendImpl(ComponentStoreImpl.kt:322)
	at com.intellij.configurationStore.ComponentStoreImpl$commitComponents$1.invokeSuspend(ComponentStoreImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:266)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
Caused by: java.util.NoSuchElementException
	at com.google.common.cache.LocalCache$HashIterator.nextEntry(LocalCache.java:4489)
	at com.google.common.cache.LocalCache$ValueIterator.next(LocalCache.java:4516)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1315)
	at com.dsoftware.ghmanager.psi.GitHubActionDataService.getState(GitHubActionDataService.kt:95)
	at com.dsoftware.ghmanager.psi.GitHubActionDataService.getState(GitHubActionDataService.kt:44)
	at com.intellij.configurationStore.ComponentStoreImplKt$getStateForComponent$3.invoke(ComponentStoreImpl.kt:883)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1$lambda$0(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:958)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$2$lambda$1(cancellableReadAction.kt:29)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:27)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:93)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:77)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:64)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:15)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:43)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:61)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:39)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.configurationStore.ComponentStoreImplKt.getStateForComponent(ComponentStoreImpl.kt:883)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:437)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$suspendImpl(ComponentStoreImpl.kt:313)
	... 10 more
```

**Comment by cunla** [comment]
Thanks, fixed.
There are multiple issues with 2024.2-EAP, however, I fixed the issue with saving the actions data.
