### ISSUE TITLE
Crash when opening a GH actions file

### ISSUE THREAD

**Issue by WarningImHack3r** [dsoftwareinc/ghactions-manager#160]
### Describe the bug
Add a screenshot if it is relevant.

**Describe the bug:**
A silent crash occurred when opening a correct random GitHub Actions yaml file:
```
java.lang.Throwable: Assertion failed: Network must not be accessed in EDT or inside read action, because this may take considerable amount of time, and write actions will be blocked during that time so user won't be able to perform tasks in the IDE
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:469)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:502)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:340)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor$Base.execute(GithubApiRequestExecutor.kt:93)
	at com.dsoftware.ghmanager.api.GhApiRequestExecutor.execute(GhApiRequestExecutor.kt:37)
	at org.jetbrains.plugins.github.api.GithubApiRequestExecutor.execute(GithubApiRequestExecutor.kt:47)
	at com.dsoftware.ghmanager.psi.GitHubActionDataService.resolveRemoteActionData(GitHubActionDataService.kt:208)
	at com.dsoftware.ghmanager.psi.GitHubActionDataService.resolveGithubAction(GitHubActionDataService.kt:189)
	at com.dsoftware.ghmanager.psi.GitHubActionDataService.resolveActions(GitHubActionDataService.kt:160)
	at com.dsoftware.ghmanager.psi.GitHubActionDataService.whenActionsLoadedWait(GitHubActionDataService.kt:111)
	at com.dsoftware.ghmanager.psi.annotator.ActionsAnnotator$doAnnotate$1.invoke(ActionsAnnotator.kt:53)
	at com.dsoftware.ghmanager.psi.annotator.ActionsAnnotator$doAnnotate$1.invoke(ActionsAnnotator.kt:50)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:31)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:271)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:845)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:31)
	at com.dsoftware.ghmanager.psi.annotator.ActionsAnnotator.doAnnotate(ActionsAnnotator.kt:50)
	at com.dsoftware.ghmanager.psi.annotator.ActionsAnnotator.doAnnotate(ActionsAnnotator.kt:31)
# Trimmed useless internal lines
```

### Steps to reproduce

Open some GitHub Actions yaml file

### Expected behavior

No crash

### Additional context

Plugin version: 2024.1.2
IDE: IU 2024.1.1
OS: macOS

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/160">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/160/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/160/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Fixed, I'll release it as 2024.1.3 next week.
Thanks for opening the issue!
