### ISSUE TITLE
com.intellij.diagnostic.PluginException: getSourceRoots(...) must not be null [Plugin: com.dsoftware.ghtoolbar]

### ISSUE THREAD

**Issue by spullara** [dsoftwareinc/ghactions-manager#179]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

#### Stack trace

com.intellij.diagnostic.PluginException: getSourceRoots(...) must not be null [Plugin: com.dsoftware.ghtoolbar]
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:502)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.NullPointerException: getSourceRoots(...) must not be null
	at com.intellij.workspaceModel.core.fileIndex.impl.NonIncrementalContributors.computeFileSets(NonIncrementalContributors.kt:160)
	at com.intellij.workspaceModel.core.fileIndex.impl.NonIncrementalContributors.updateIfNeeded(NonIncrementalContributors.kt:50)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(Workspac

### Additional context

Plugin version: 2024.2.8
IDE: IntelliJ IDEA 2024.2.1 (IU-242.21829.142)
OS: macOS 14.6.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/179">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/179/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/179/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
How do you get this stacktrace? what do you do?

**Comment by cunla** [comment]
Can you post the entire stacktrace here?

**Comment by cunla** [comment]
Closing due to lack of activity.
Please reopen if needed
