### ISSUE TITLE
java.lang.RuntimeException: Cannot invoke (class=, method=fileOpened, topic=FileEditorManagerListener)

### ISSUE THREAD

**Issue by anton-demchuchen** [dsoftwareinc/ghactions-manager#180]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

Unhandled exception in [ComponentManager(ProjectImpl@1747029670), CoroutineName(EditorComposite(file=smoke_core.yaml)), ModalityState.ANY, ClientId(value=Host), Dispatchers.Default]

#### Stack trace

java.lang.RuntimeException: Cannot invoke (class=, method=fileOpened, topic=FileEditorManagerListener)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:699)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:445)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:424)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:483)
	at jdk.proxy2/jdk.proxy2.$Proxy136.fileOpened(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.EditorComposite$handleModel$3$2$1.invoke(EditorComposite.kt:274)
	at com.intellij.openapi.fileEditor.impl.EditorComposite$handleModel$3$2$1.invoke(EditorComposite.kt:273)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:339)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:232)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.corou

### Additional context

Plugin version: 2024.2.8
IDE: PyCharm 2024.2.1 (PY-242.21829.153)
OS: macOS 14.5

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/180">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/180/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/180/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Hi Anton, do you mind pasting here the full stacktrace you are getting?

**Comment by cunla** [comment]
I will publish a fix to the error reporter to submit the relevant part of the stack trace
