### ISSUE TITLE
java.lang.NullPointerException: null cannot be cast to non-null type com.dsoftware.ghmanager.data.RepositoryContext

### ISSUE THREAD

**Issue by BalbekovAD** [dsoftwareinc/ghactions-manager#182]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

#### Stack trace

java.lang.NullPointerException: null cannot be cast to non-null type com.dsoftware.ghmanager.data.RepositoryContext
	at com.dsoftware.ghmanager.ui.context.RepoContextLoadingPanelFactory$Companion$ContentController.update(RepoContextLoadingPanelFactory.kt:63)
	at com.dsoftware.ghmanager.ui.context.RepoContextLoadingPanelFactory$Companion$ContentController.access$update(RepoContextLoadingPanelFactory.kt:33)
	at com.dsoftware.ghmanager.ui.context.RepoContextLoadingPanelFactory$Companion$ContentController$1.onLoadingCompleted(RepoContextLoadingPanelFactory.kt:56)
	at com.dsoftware.ghmanager.ui.context.RepoContextLoader.load$lambda$2(RepoContextLoader.kt:87)
	at com.dsoftware.ghmanager.ui.ToolbarUtilKt.handleOnEdt$lambda$0(ToolbarUtil.kt:52)
	at com.dsoftware.ghmanager.ui.ToolbarUtil.getEDTExecutor$lambda$1$lambda$0(ToolbarUtil.kt:64)
	at com.dsoftware.ghmanager.ui.ToolbarUtil.getEDTExecutor$lambda$1(ToolbarUtil.kt:64)
	at com.dsoftware.ghmanager.ui.context.RepoContextLoader.dispose(RepoContextLoader.kt:105)
	at com.dsoftware.ghmanager.ui.GhActionsMgrToolWindowContent.createRepoWorkflowsPanels(GhActionsMgrToolWindowContent.kt:126)
	at com.dsoftware.ghmanager.ui.GhActionsMgrToolWindowContent.createContent$lambda$1(GhActionsMgrToolWindowContent.kt:106)

### Additional context

Plugin version: 2024.2.10
IDE: GoLand 2024.3 EAP (GO-243.15521.25)
OS: Windows 11.0

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/182">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/182/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/182/pledge.svg">
</picture>
</a>

**Comment by cunla** [comment]
Thanks for reporting this. 
Can you elaborate when this happens?
I added extra checks, but generally speaking, the flow should not get there.

**Comment by cunla** [comment]
i published a fix 2024.2.11, should be available later this week.
