### ISSUE TITLE
com.intellij.diagnostic.PluginException: null cannot be cast to non-null type org.jetbrains.yaml.psi.YAMLMapping [Plugin: com.dsoftware.ghtoolbar]

### ISSUE THREAD

**Issue by anton-demchuchen** [dsoftwareinc/ghactions-manager#199]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

#### Stack trace

com.intellij.diagnostic.PluginException: null cannot be cast to non-null type org.jetbrains.yaml.psi.YAMLMapping [Plugin: com.dsoftware.ghtoolbar]
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:502)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.NullPointerException: null cannot be cast to non-null type org.jetbrains.yaml.psi.YAMLMapping
	at com.dsoftware.ghmanager.psi.model.DispatchableWorkflowInput$Companion.fromYaml(DispatchableWorkflow.kt:27)
	at com.dsoftware.ghmanager.psi.ProjectStartup.registerDispatchableWorkflow(ProjectStartup.kt:83)
	at com.dsoftware.ghmanager.psi.ProjectStartup.scanWorkflowFile$lambda$5(ProjectSta

### Additional context

Plugin version: 2024.2.8
IDE: PyCharm 2024.2.1 (PY-242.21829.153)
OS: macOS 15.0.1

**Comment by cunla** [comment]
This was fixed in later versions of the plugin. Please update.
