### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: Range [-1, 96) out of bounds for length 96

### ISSUE THREAD

**Issue by SpellForce78** [dsoftwareinc/ghactions-manager#200]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

#### Stack trace

	at com.dsoftware.ghmanager.psi.ProjectStartup.registerDispatchableWorkflow(ProjectStartup.kt:89)
	at com.dsoftware.ghmanager.psi.ProjectStartup.scanWorkflowFile$lambda$5(ProjectStartup.kt:62)
	at com.dsoftware.ghmanager.psi.ProjectStartup.scanWorkflowFile(ProjectStartup.kt:50)
	at com.dsoftware.ghmanager.psi.ProjectStartup$execute$2.fileOpened(ProjectStartup.kt:32)

### Additional context

Plugin version: 2024.3.3
IDE: IntelliJ IDEA 2024.3.1.1 (IU-243.22562.218)
OS: macOS 15.2

**Comment by cunla** [comment]
Hi, apologies, I have missed the notification for this issue. I will investigate today.

**Comment by cunla** [comment]
Fixed in 2024.3.4
