### ISSUE TITLE
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details

### ISSUE THREAD

**Issue by Navarro-321** [dsoftwareinc/ghactions-manager#201]
### Describe the bug 
Add a screenshot if it is relevant.

**Describe the bug:**

#### Stack trace

	at com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanelWrapper$special$$inlined$observable$1.afterChange(Delegates.kt:37)
	at com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanelWrapper.setContent(LogConsolePanelWrapper.kt:38)
	at com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanelWrapper.onReset(LogConsolePanelWrapper.kt:78)
	at com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanelWrapper.access$onReset(LogConsolePanelWrapper.kt:32)
	at com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanelWrapper$2.invoke(LogConsolePanelWrapper.kt:57)
	at com.dsoftware.ghmanager.ui.panels.logs.LogConsolePanelWrapper$2.invoke(LogConsolePanelWrapper.kt:57)
	at com.dsoftware.ghmanager.viewmodel.ViewModel._init_$lambda$9(ViewModel.kt:21)
	at com.dsoftware.ghmanager.viewmodel.ListSelectionHolder$special$$inlined$observable$1.afterChange(Delegates.kt:35)
	at com.dsoftware.ghmanager.viewmodel.ListSelectionHolder.setSelection(SelectionHolders.kt:15)
	at com.dsoftware.ghmanager.data.RepositoryContext.resetAllData(RepositoryContext.kt:126)
	at com.dsoftware.ghmanager.actions.dispatch.WorkflowDispatchDialogPanel.show$lambda$5$lambda$4$lambda$1(WorkflowDispatchDialog.kt:53)
	at com.dsoftware.ghmanager.actions.dispatch.WorkflowDispatchDialogPanel.show$lambda$5$lambda$4$lambda$2(WorkflowDispatchDialog.kt:47)

### Additional context

Plugin version: 2024.3.3
IDE: PyCharm 2024.3.1.1 (PY-243.22562.220)
OS: macOS 15.2

**Comment by cunla** [comment]
Thanks for reporting this. I'll have a look today

**Comment by cunla** [comment]
Fixed in 2024.3.4
